name: Build and Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        default: 'latest'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    # 确定发布标签
    - name: Determine Release Tag  
      id: determine-tag
      run: |
        if [ '${{ github.event_name }}' == 'release' ]; then
          echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        else
          echo "RELEASE_TAG=${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_ENV
        fi
        echo "Using release tag: ${RELEASE_TAG}"

    # 检查是否存在同名发布版本
    - name: Check existing release
      id: check_release
      run: |
        tag="${RELEASE_TAG}"
        # 通过GitHub API查询是否存在同名release
        release_response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag")
        release_id=$(echo "$release_response" | jq -r '.id')
        
        if [ "$release_id" != "null" ]; then
          echo "Found existing release with ID $release_id"
          echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          echo "EXISTING_RELEASE_ID=$release_id" >> $GITHUB_ENV
        else
          echo "No existing release found for tag $tag"
          echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
        fi
        
    # 创建新的GitHub Release（仅当不存在时）
    - name: Create Release
      id: create_release
      if: env.RELEASE_EXISTS == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: |
            Release created by GitHub Actions.
            
            **Tag:** ${{ env.RELEASE_TAG }}
            **Build Date:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')
            **Commit:** ${{ github.sha }}
            
            ## 包含的平台（统一ZIP格式）
            - Windows AMD64
            - Linux AMD64/ARM64/ARMv7/386
            - macOS AMD64/ARM64
            
            所有平台都使用ZIP格式打包，方便跨平台使用。
          draft: false
          prerelease: false
          
    # 设置发布版本ID（用于上传资产）
    - name: Set Release ID
      id: set_release_id
      run: |
        if [ "${{ env.RELEASE_EXISTS }}" == "true" ]; then
          echo "UPLOAD_RELEASE_ID=${{ env.EXISTING_RELEASE_ID }}" >> $GITHUB_ENV
        else
          echo "UPLOAD_RELEASE_ID=${{ steps.create_release.outputs.id }}" >> $GITHUB_ENV
        fi
        echo "Will upload to release ID: ${UPLOAD_RELEASE_ID}"
    
    - name: Build and package for multiple platforms
      run: |
        # Define the platforms and their configurations
        # Format: "GOOS/GOARCH/GOARM" (GOARM is optional)
        platforms=(
          "windows/amd64" 
          "linux/amd64" 
          "linux/arm64" 
          "linux/arm/7"  # ARMv7 with GOARM=7
          "linux/386" 
          "darwin/amd64"
          "darwin/arm64"
        )
        
        # Navigate to the gmqttd directory
        cd cmd/gmqttd || { echo "Failed to enter gmqttd directory"; exit 1; }
        
        # Replace IP addresses in the necessary files if needed
        if [ -f "thingspanel.yml" ]; then
          # Use sed to replace 47.115.213.71 with 127.0.0.1
          sed -i 's/47.115.213.71/127.0.0.1/g' thingspanel.yml
        fi
        
        # Create dist directory for builds
        mkdir -p ../../dist
        
        for platform in "${platforms[@]}"; do
          # Split the platform string
          IFS="/" read -r os arch arm_version <<< "$platform"
          
          # Set build environment variables
          export GOOS=$os
          export GOARCH=$arch
          export CGO_ENABLED=0
          
          # Set GOARM if specified
          if [ ! -z "$arm_version" ]; then
            export GOARM=$arm_version
            platform_suffix="$os-$arch-v$arm_version"
          else
            unset GOARM
            platform_suffix="$os-$arch"
          fi
          
          echo "Building for $GOOS/$GOARCH${GOARM:+/v$GOARM}..."
          
          # Create output directory
          mkdir -p "../../dist/$platform_suffix"
          
          # Copy necessary files
          cp -r certs "../../dist/$platform_suffix/" 2>/dev/null || echo "No certs directory found"
          cp thingspanel.yml "../../dist/$platform_suffix/" 2>/dev/null || echo "No thingspanel.yml found"
          cp default_config.yml "../../dist/$platform_suffix/" 2>/dev/null || echo "No default_config.yml found"
          
          # Adjust output file name for Windows
          if [ "$os" == "windows" ]; then
             output_file="../../dist/$platform_suffix/thingspanel-gmqtt.exe"
          else
             output_file="../../dist/$platform_suffix/thingspanel-gmqtt"
          fi
          
          # Build for each platform
          go build -o "$output_file"
          
          # Check if build was successful
          if [ $? -ne 0 ]; then
            echo "Failed to build for $GOOS/$GOARCH${GOARM:+/v$GOARM}, skipping..."
            rm -rf "../../dist/$platform_suffix"
            continue
          fi
          
          # Create archive name (all platforms use zip)
          archive_name="thingspanel-gmqtt-$platform_suffix.zip"
          # Package into zip for all platforms
          (cd ../../dist && zip -r "../$archive_name" "$platform_suffix")
          
          echo "Created archive: $archive_name"
        done
        
        # Navigate back to root directory
        cd ../..
        
        # List all created archives  
        echo "Listing created archives:"
        ls -la *.zip 2>/dev/null || echo "No archives found in current directory"
        echo "Current working directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
    
    # 上传构建产物到GitHub Release
    - name: Upload Release Assets
      id: upload-release-assets
      run: |
        echo "Current working directory: $(pwd)"
        echo "Looking for zip files..."
        ls -la *.zip 2>/dev/null || echo "No zip files found in root directory"
        
        # 遍历所有ZIP打包文件并上传
        found_files=false
        for asset in ./thingspanel-gmqtt-*.zip; do
          if [ -f "$asset" ]; then
            found_files=true
            asset_name=$(basename "$asset")
            echo "Uploading $asset_name..."
            
            # 设置ZIP文件的Content-Type
            content_type="application/zip"
            
            # 通过GitHub API上传文件到release
            echo "Uploading to release ID: ${UPLOAD_RELEASE_ID}"
            upload_response=$(curl -s -w "%{http_code}" -XPOST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $content_type" \
              --data-binary "@$asset" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${UPLOAD_RELEASE_ID}/assets?name=$asset_name")
            
            http_code=${upload_response: -3}
            if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
              echo "✅ Successfully uploaded $asset_name (HTTP $http_code)"
            else
              echo "❌ Failed to upload $asset_name (HTTP $http_code)"
              echo "Response: ${upload_response%???}"
              exit 1
            fi
          fi
        done
        
        if [ "$found_files" = false ]; then
          echo "❌ No zip files found to upload!"
          exit 1
        fi
