name: Docker Image CI-1.0.0

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: thingspanel/thingspanel-gmqtt:v1.0.0

    - name: Login to Aliyuncs Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.IMAGE_USER }}
        password: ${{ secrets.IMAGE_PASS }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Aliyuncs Docker Hub
      run: |
         skopeo copy docker://docker.io/thingspanel/thingspanel-gmqtt:v1.0.0 docker://registry.cn-hangzhou.aliyuncs.com/thingspanel/thingspanel-gmqtt:v1.0.0
